{
 "title": "Nginx",
 "description": "Grafana Dashboard for Nginx Web Server.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up,instance)"
    }
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Nginx Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Connections Accepted",
   "type": "timeseries",
   "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{instance=~\"$instance*\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Active Connections[accepted]",
   "type": "bargauge",
   "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance*\"}\t",
     "legendFormat": "{{instance }}"
    }
   ]
  },
  {
   "title": "Nginx Waiting Connections",
   "type": "stat",
   "description": "The current number of connections from clients that are in the Idle / Waiting state.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance*\"}\t",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Handled Request",
   "type": "timeseries",
   "description": "The total number of handled connections from clients since the nginx master process started. This will be lower than accepted only in cases where a connection is dropped before it is handled.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled{instance=~\"$instance*\"}\t[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Requests",
   "type": "timeseries",
   "description": "The total number of client requests since the nginx master process started. A request is an application-level (HTTP, etc.) event. It occurs when a client requests a resource via the application protocol. A single connection can (and often does) make many requests. So most of the time, there are more requests than accepted/handled connections.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=~\"$instance*\"}\t[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Writing",
   "type": "stat",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance*\"}\t",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Nginx Reading",
   "type": "stat",
   "description": "The current number of (accepted) connections from clients where nginx is reading the request. Measured at the time the status module was queried.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance*\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}