---
- name: Start nomad
  listen: "start nomad"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nomad
    state: started
    enabled: true

- name: Restart nomad
  listen: "restart nomad"
  become: true
  ansible.builtin.systemd:
    name: nomad
    state: restarted
