{
 "title": "Nomad Cluster Overview",
 "description": "Nomad cluster dashboard. Using built in nomad's exporter and loki.",
 "tags": [
  "nomad",
  "host",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime,datacenter)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"},instance)"
    }
   },
   { "name": "datasource_logs", "label": "Datasource Logs", "query": "loki" },
   {
    "name": "nomad_job",
    "label": "Nomad Job",
    "query": {}
   },
   {
    "name": "stream_file",
    "label": "Stream File",
    "query": {}
   },
   { "name": "log_filter", "label": "Log Filter" },
   {
    "name": "server_host",
    "query": {
     "query": "label_values(nomad_raft_commitTime,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Allocated CPU  ($datacenter)",
   "type": "piechart",
   "description": "In the whole cluster",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_cpu_allocated) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    },
    {
     "expr": "sum(nomad_client_unallocated_cpu)",
     "legendFormat": "Free cluster CPU"
    }
   ]
  },
  {
   "title": "OOM kills",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "nomad_client_allocs_oom_killed{}",
     "legendFormat": "oom"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 - 3600000",
     "legendFormat": "from"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 + 3600000",
     "legendFormat": "to"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nomad_metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_pending", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_complete{}",
     "legendFormat": "complete"
    },
    {
     "expr": "nomad_nomad_job_summary_failed{}",
     "legendFormat": "failed"
    },
    { "expr": "nomad_nomad_job_summary_lost{}", "legendFormat": "lost" },
    {
     "expr": "nomad_nomad_job_summary_starting{env=\"$env\"}",
     "legendFormat": "starting"
    },
    {
     "expr": "nomad_nomad_job_summary_queued{env=\"$env\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "nomad_nomad_job_summary_running{env=\"$env\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "Dead" }
   ]
  },
  {
   "title": "Allocated MEM ($datacenter)",
   "type": "piechart",
   "description": "In whole cluster",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_memory_allocated) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    },
    {
     "expr": "sum(nomad_client_host_memory_free)",
     "legendFormat": "Free cluster MEM"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(instance) (nomad_raft_commitTime)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_uptime{datacenter=~\"$datacenter\", instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Free memmory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", instance=~\"$host\"} /nomad_client_host_memory_total{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Free Disk Space ($host)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", instance=~\"$host\"}) by (disk) / max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", instance=~\"$host\"}) by (disk) ",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Allocation status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 14 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$host\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "Unalocated CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$host\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", instance=~\"$host\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Unalocated Mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$host\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", instance=~\"$host\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", instance=~\"$host\"})"
    }
   ]
  },
  { "title": "Job Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Logs Nomad Jobs ($datacenter)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{instance=~\"$host\", nomad_job=~\"$nomad_job\", filename=~\".*$stream_file.*\"} |= `$log_filter`"
    }
   ]
  },
  { "title": "RAFT status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_commitTime{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nomad_raft_apply{}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Node Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Logs Nomad Clients Node",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{instance=~\"$host\", unit=\"nomad.service\"} |= `$log_filter`"
    }
   ]
  },
  {
   "title": "Logs Nomad Servers Node",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{instance=~\"$server_host\", unit=\"nomad.service\"} |= `$log_filter`"
    }
   ]
  }
 ]
}