---
- name: Add Grafana repo
  ansible.builtin.yum_repository:
    name: grafana
    description: Grafana repo
    baseurl: https://rpm.grafana.com
    gpgcheck: no
    enabled: yes

- name: Install the latest version of Grafana Alloy
  ansible.builtin.dnf:
    name: alloy
    state: latest
  notify: start alloy

- name: Create Grafana Alloy Config
  ansible.builtin.template:
    src: "etc/alloy/config.alloy.j2"
    dest: /etc/alloy/config.alloy
    mode: 0644
  notify: restart alloy

# - name: Copy Grafana Alloy Config
#   ansible.builtin.copy:
#     src: ./
#     dest: /
#   notify: restart alloy