apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus_main
  url: http://prometheus:9090
  isDefault: true
  editable: true
- name: VictoriaMetrics
  type: prometheus
  uid: victoriametrics_main
  url: http://victoriametrics:8428
  isDefault: false
  editable: true
- name: Loki
  type: loki
  access: proxy
  uid: loki_main
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false